<?php
require('Application.php');
require('../header.php');
echo "<font face=\"arial\">";
echo "<center>";
echo "<table width=\"100%\" border=\"0\" cellspacing=\"5\" cellpadding=\"5\">";
echo "<tr valign=\"top\">";
echo "<td width=\"50%\">";
echo "<p><font face=\"arial, helvetica, sans-serif\" size=\"-1\"><b>Access Your Messages from Your NBX Telephones</b></font></p>";
echo "<ol>";
echo "<li><font face=\"arial, helvetica, sans-serif\" size=\"-1\">Pick up your handset and press MSG</font></li>";
echo "<li><font face=\"arial, helvetica, sans-serif\" size=\"-1\">Enter your password and then press #</font></li>";
echo "</ol>";
echo "<p><font face=\"arial, helvetica, sans-serif\" size=\"-1\"><b>Access Your Messages from any NBX Telephone</b></font></p>";
echo "<ol>";
echo "<li><font face=\"arial, helvetica, sans-serif\" size=\"-1\">Pick up your handset and press MSG</font></li>";
echo "<li><font face=\"arial, helvetica, sans-serif\" size=\"-1\">At the password prompt, press *</font></li>";
echo "<li><font face=\"arial, helvetica, sans-serif\" size=\"-1\">When prompted, enter your estention number</font></li>";
echo "<li><font face=\"arial, helvetica, sans-serif\" size=\"-1\">Enter your password and then press #</font></li>";
echo "</ol>";
echo "<p><font face=\"arial, helvetica, sans-serif\" size=\"-1\"><b>Access Your Messages from an External Telephone</b></font></p>";
echo "<ol>";
echo "<li><font face=\"arial, helvetica, sans-serif\" size=\"-1\">Dial your company's telephone number</font></li>";
echo "<li><font face=\"arial, helvetica, sans-serif\" size=\"-1\">If the automated attendant answers, press * twice during the greeting message</font></li>";
echo "<li><font face=\"arial, helvetica, sans-serif\" size=\"-1\">If your receptionist answers, ask to be transfered to your voicemail. During the greeting message, press *</font></li>";
echo "<li><font face=\"arial, helvetica, sans-serif\" size=\"-1\">When prompted, enter your extension number and password, and then press # </font></li>";
echo "</ol>";
echo "<p><font face=\"arial, helvetica, sans-serif\" size=\"-1\"><b>Mailbox Options</b></font></p>";
echo "<ol>";
echo "<li><font face=\"arial, helvetica, sans-serif\" size=\"-1\">Pickup your handset and press MSG</font></li>";
echo "<li><font face=\"arial, helvetica, sans-serif\" size=\"-1\">When prompted, enter your password</font></li>";
echo "</ol>";
echo "<p><font face=\"arial, helvetica, sans-serif\" size=\"-1\">Press 9 to select these options: </font>";
echo "<ul>";
echo "<font face=\"arial, helvetica, sans-serif\" size=\"-1\"> <b>Press 1</b> to change your name announcement/personal greeting<br>";
echo "<b>Press 2</b> to change your password<br>";
echo "<b>Press 3</b> to create or edit group lists<br>";
echo "<b>Press 4</b> to set up Offsite Notification options </font>";
echo "</ul>";
echo "<p><font face=\"arial, helvetica, sans-serif\" size=\"-1\"><b>Change Your Voicemail Password</b></font></p>";
echo "<ol>";
echo "<li><font face=\"arial, helvetica, sans-serif\" size=\"-1\">Pickup your handset and press MSG</font></li>";
echo "<li><font face=\"arial, helvetica, sans-serif\" size=\"-1\">When prompted, enter your password</font></li>";
echo "<li><font face=\"arial, helvetica, sans-serif\" size=\"-1\">Press 9 for mailbox options</font></li>";
echo "<li><font face=\"arial, helvetica, sans-serif\" size=\"-1\">Press 2 to select the Change Password option</font></li>";
echo "</ol>";
echo "<p align=\"left\"><font face=\"arial, helvetica, sans-serif\" size=\"-1\"><i>Use the same initial password for voicemail that you use to access NetSet</i></font></p>";
echo "</td>";
echo "<td width=\"50%\">";
echo "<p><font face=\"arial, helvetica, sans-serif\" size=\"-1\"><b>Forward Incoming Calls Directly to Voice Mail</b></font></p>";
echo "<p><font face=\"arial, helvetica, sans-serif\" size=\"-1\">Press the FWD MAIL button of your NBX telephone. While FWD MAIL is active, incoming calls ring once before forwarding.</font></p>";
echo "<p><font face=\"arial, helvetica, sans-serif\" size=\"-1\">See the NBX Business Telephone Guide or MetSet User Help for more information.</font></p>";
echo "<p><font face=\"Arial, Helvetica, sans-serif\" size=\"-1\"><b>Message Playback Options</b></font></p>";
echo "<p><font face=\"Arial, Helvetica, sans-serif\" size=\"-1\">While listening to a message, you have these options:</font></p>";
echo "<ul>";
echo "<p><font face=\"Arial, Helvetica, sans-serif\" size=\"-1\"> <b>Press 1</b>";
echo " to listen to the first message<br>";
echo "<b>Press 2</b> to save the current message<br>";
echo "<b>Press 3</b> to delete the current message<br>";
echo "<b>Press 4</b> to reply to the sender of current message<br>";
echo "<b>Press 5</b> to forward the current message<br>";
echo "<b>Press 6</b> to hear date, time, and sender info<br>";
echo "<b>Press 7</b> to skip back five seconds in current message<br>";
echo "<b>Press 8</b> to pause current message<br>";
echo "<b>Press 9</b> to skip forward five seconds in current message<br>";
echo "<b>Press #</b> to skip to next message<br>";
echo "<b>Press *</b> to exit to the main menu</font></p>";
echo "</ul>";
echo "<p><font face=\"Arial, Helvetica, sans-serif\" size=\"-1\"><b>Forward a Message</b></font></p>";
echo "<ol>";
echo "<li><font face=\"Arial, Helvetica, sans-serif\" size=\"-1\">While you are";
echo "listening to the message, press 5</font></li>";
echo "<li><font face=\"Arial, Helvetica, sans-serif\" size=\"-1\">The system prompts";
echo " you to enter an extension or group number.You can add as many destinations";
echo " as you want.</font></li>";
echo "<li><font face=\"Arial, Helvetica, sans-serif\" size=\"-1\">After you have";
echo " entered all destinations, press # to begin recording a forwarding comment.</font></li>";
echo "<li><font face=\"Arial, Helvetica, sans-serif\" size=\"-1\">When you finish";
echo " recording the comment, press# for more options, or hang up.</font></li>";
echo "</ol>";
echo "</td>";
echo "</tr>";
echo "</table>";
require('../trailer.php');
?>
