<?php
require('Application.php');
require('../../header.php');
echo "<center>";
echo "<p>";
echo "<font face=\"arial\">";
echo "<center>";
echo "<font face=\"arial\" size=\"+1\"><b>Knowledge Base Search Form</b></font>";
echo "<p>";
echo "<form action=\"results.php\" method=\"post\">";
echo "<table>";
echo "<tr>";
echo "<td>Author:</td>";
echo "<td><input type=\"Text\" name=\"author\"></td>";
echo "</tr>";
echo "<tr>";
echo "<td>Title:</td>";
echo "<td><input type=\"text\" name=\"title\"></td>";
echo "</tr>";
echo "<tr>";
echo "<td>Keyword:</td>";
echo "<td><input type=\"text\" name=\"keyword\"></td>";
echo "</tr>";
echo "<tr>";
echo "<td>Subject:</td>";
echo "<td><input type=\"text\" name=\"subject\"></td>";
echo "</tr>";
echo "<tr>";
echo "<td>Updated In:</td>";
echo "<td><select name=\"selectdate\">";
echo "<option value=\"week\">Past Week</option>";
echo "<option value=\"month\">Past Month</option>";
echo "<option value=\"all\">All</option>";
echo "</select></td>";
echo "</td>";
echo "</tr>";
echo "<tr>";
echo "<td colspan=\"2\" align=\"center\"><hr width=\"80%\" noshade>";
echo "<input type=\"submit\" name=\"\" value=\"Submit\">";
echo "<input type=\"reset\"></td>";
echo "</tr>";
echo "</table>";
echo "</center>";
echo "</form>";
require('../../trailer.php');
?>
